# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 44cbe16
_src_path: https://github.com/maurosilber/python-lib-template
github_username: ramirohar
license: MIT
max_python_version: '3.13'
min_python_version: '3.7'
platforms:
- linux-64
- win-64
project_description: Rpc protocol for OpenMV cameras
project_name: openmv_rpc_protocol
project_slug: rpc_protocol
your_email: ramirohar@gmail.com
your_name: Ramiro Harguiteguy
