[workspace]
authors = ["Ramiro Harguinteguy <ramirohar@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "openmv_rpc_protocol"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.4,<3"
ipykernel = ">=6.29.5,<7"
pyserial = ">=3.5,<4"
pandas = ">=2.2.3,<3"
