name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
        with:
          environments: lint
      - run: pixi run --environment lint lint-all --show-diff-on-failure

test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - test-py37
          - test-py38
          - test-py39
          - test-py310
          - test-py311
          - test-py312
          - test-py313
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
        with:
          environments: ${{ matrix.environment }}
      - run: pixi run --environment ${{ matrix.environment }} test


  build:
    needs: [test, lint]

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/openmv_rpc_protocol
    permissions:
      id-token: write  # for trusted publising to PyPI

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.5
        with:
          environments: build
      - name: Build the package
        run: pixi run --environment build build
      - name: Publish to PyPI
        if: github.ref_type == 'tag'
        run: pixi run --environment build publish
